#!/usr/bin/env bash
# Regenerate the inlined Sutra logo assets used by obsidian-mcp.
#
# The runtime container ships only dist/ + node_modules/ (see Dockerfile), so
# the logo bytes cannot be served from assets/ at runtime — they are inlined as
# base64 here and bundled into dist/main.js by tsup. This script resizes the
# master assets/logo.png (via macOS `sips`) into the three sizes the service
# uses and re-emits src/branding/logoAssets/index.ts.
#
#   32px   -> /favicon.ico
#   96px   -> serverInfo.icons data-URI (kept small; sent on every initialize)
#   192px  -> /icon.png + /apple-touch-icon.png
#
# It also renders the meeting bot's camera tile — a full-bleed 1280x720 JPEG
# (Recall requires JPEG / 16:9 / <=1.3MB) that the bot broadcasts as its webcam
# via automatic_video_output — and emits src/branding/botCamera/index.ts.
#
# Requires macOS `sips` and `base64`. Self-sufficient — run from anywhere:
#   ./scripts/obsidian-mcp/gen-logo-assets.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
ASSETS="$REPO_ROOT/services/obsidian-mcp/assets"
OUT="$REPO_ROOT/services/obsidian-mcp/src/branding/logoAssets/index.ts"
OUT_BOT="$REPO_ROOT/services/obsidian-mcp/src/branding/botCamera/index.ts"
SRC="$ASSETS/logo.png"

[ -f "$SRC" ] || { echo "missing master logo: $SRC" >&2; exit 1; }
command -v sips >/dev/null 2>&1 || { echo "sips not found (this script is macOS-only)" >&2; exit 1; }

for s in 32 96 192; do
  sips -z "$s" "$s" "$SRC" --out "$ASSETS/icon-$s.png" >/dev/null
done

b64() { base64 < "$1" | tr -d '\n'; }
B32="$(b64 "$ASSETS/icon-32.png")"
B96="$(b64 "$ASSETS/icon-96.png")"
B192="$(b64 "$ASSETS/icon-192.png")"

# Bot camera tile. Full-bleed (scale to 1280 wide, crop centre to 1280x720) so
# it is one continuous image with no letterbox seam, then JPEG at quality 92.
sips -Z 1280 "$SRC" -s format png --out "$ASSETS/.bot-big.png" >/dev/null
sips -c 720 1280 "$ASSETS/.bot-big.png" --out "$ASSETS/.bot-crop.png" >/dev/null
sips -s format jpeg -s formatOptions 92 "$ASSETS/.bot-crop.png" --out "$ASSETS/bot-camera.jpg" >/dev/null
rm -f "$ASSETS/.bot-big.png" "$ASSETS/.bot-crop.png"
BJPG="$(b64 "$ASSETS/bot-camera.jpg")"

mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<EOF
// GENERATED by scripts/obsidian-mcp/gen-logo-assets.sh — do not edit by hand.
// Source: services/obsidian-mcp/assets/logo.png (the Sutra mark).
//
// The runtime image ships only dist/ + node_modules/ (see Dockerfile), so the
// logo bytes are inlined here and bundled into dist/main.js rather than copied
// as a static asset. Sizes: 32px (favicon), 96px (serverInfo data-URI), 192px
// (icon.png / apple-touch-icon). Excluded from biome (see biome.json) because
// it is a generated base64 blob.

const ICON_32_BASE64 = "$B32";
const ICON_96_BASE64 = "$B96";
const ICON_192_BASE64 = "$B192";

/** 32x32 PNG, served at /favicon.ico. */
export const logoFavicon = Buffer.from(ICON_32_BASE64, "base64");

/** 192x192 PNG, served at /icon.png and /apple-touch-icon.png. */
export const logoIcon = Buffer.from(ICON_192_BASE64, "base64");

/** 96x96 PNG as a data-URI, carried in serverInfo.icons. */
export const logoIconDataUri = "data:image/png;base64," + ICON_96_BASE64;
EOF

mkdir -p "$(dirname "$OUT_BOT")"
cat > "$OUT_BOT" <<EOF
// GENERATED by scripts/obsidian-mcp/gen-logo-assets.sh — do not edit by hand.
// Source: services/obsidian-mcp/assets/logo.png (the Sutra mark).
//
// The meeting bot's camera tile: a 1280x720 JPEG the bot broadcasts as its
// webcam via Recall's automatic_video_output (JPEG / 16:9 / <=1.3MB). Raw
// base64 with NO data: prefix — Recall's b64_data wants the bare string.
// Excluded from biome (see biome.json) because it is a generated base64 blob.

export const botCameraJpegBase64 = "$BJPG";
EOF

echo "wrote $OUT"
echo "wrote $OUT_BOT"
