# ─── Obsidian MCP server (Phase 2) ──────────────────────────────────────────
#
# A Cloud Run service that exposes the Phase 1 CouchDB vault to Claude over
# the Model Context Protocol (MCP). Connection path:
#
#   Claude  ──HTTPS──▶  mcp.<domain>  (Cloudflare Access policy)
#                         │
#                         ▼
#                       Cloudflare Tunnel (same tunnel as Phase 1, second
#                       ingress hostname added on the VM by hand —
#                       scripts/obsidian-mcp/add-tunnel-hostname.sh)
#                         │
#                         ▼
#                       Cloud Run service in this same project
#                         │
#                         ▼
#                       Phase 1 CouchDB at https://vault.<domain>
#
# The server reads/writes documents in the same database as the LiveSync
# clients. It holds the LiveSync E2EE passphrase (in Secret Manager) so it
# can encrypt and decrypt notes the same way LiveSync does. That makes the
# auth layer in front of Cloud Run security-critical: anyone who can reach
# the MCP endpoint with a valid identity can read the entire vault.
#
# The auth design is deliberately portable — see docs/obsidian-mcp/auth.md.
# Today: Cloudflare Access JWT + a server-side bearer-token defence-in-depth.
# Tomorrow: swap a different AuthProvider (IAP, OIDC, etc.) without
# rewriting the server.

# ─── Service account ────────────────────────────────────────────────────────
#
# Dedicated SA for the Cloud Run service. Three secret-scoped grants below
# are the only IAM it gets. No project-wide roles.

resource "google_service_account" "obsidian_mcp" {
  account_id   = "obsidian-mcp"
  display_name = "Obsidian MCP server"
  description  = "Service account for the Cloud Run MCP server. Reads three Secret Manager secrets only."
}

# ─── Artifact Registry repo for the server image ────────────────────────────
#
# A single Docker repo per service. Cloud Build / local docker pushes images
# tagged with the git short SHA into this repo; the deploy script flips the
# Cloud Run revision to a new tag.

resource "google_project_service" "artifact_registry" {
  service            = "artifactregistry.googleapis.com"
  disable_on_destroy = false
}

resource "google_project_service" "cloud_run" {
  service            = "run.googleapis.com"
  disable_on_destroy = false
}

resource "google_artifact_registry_repository" "obsidian_mcp" {
  location      = var.gcp_region
  repository_id = "obsidian-mcp"
  description   = "Container images for the Obsidian MCP Cloud Run service."
  format        = "DOCKER"

  depends_on = [google_project_service.artifact_registry]
}

# ─── CouchDB user dedicated to the MCP server ───────────────────────────────
#
# The Phase 1 CouchDB admin password is reused only as a bootstrap credential
# to provision a scoped user (see scripts/obsidian-mcp/create-couchdb-user.sh).
# The MCP server itself only ever sees this scoped user's credentials.
#
# Why scoped: the admin user has rights to drop databases, reset passwords,
# and rewrite cluster config. The MCP server only needs RW on the obsidian DB.
# A compromised Cloud Run revision shouldn't be able to take CouchDB down.
#
# `special = false` keeps us out of shell-escaping trouble (this password is
# interpolated into a curl URL inside create-couchdb-user.sh).

resource "random_password" "obsidian_mcp_couchdb_password" {
  length  = 32
  special = false
}

resource "google_secret_manager_secret" "obsidian_mcp_couchdb_password" {
  secret_id = "obsidian-mcp-couchdb-password"

  replication {
    auto {}
  }

  depends_on = [google_project_service.secret_manager]
}

resource "google_secret_manager_secret_version" "obsidian_mcp_couchdb_password" {
  secret      = google_secret_manager_secret.obsidian_mcp_couchdb_password.id
  secret_data = random_password.obsidian_mcp_couchdb_password.result
}

resource "google_secret_manager_secret_iam_member" "obsidian_mcp_couchdb_password_accessor" {
  secret_id = google_secret_manager_secret.obsidian_mcp_couchdb_password.id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.obsidian_mcp.email}"
}

# ─── LiveSync E2EE passphrase ───────────────────────────────────────────────
#
# This is the passphrase you set in Obsidian → Self-hosted LiveSync → E2EE
# during Phase 1 client setup. It's NOT generated by Terraform — there's no
# way for Terraform to know what you typed into the Obsidian client. We
# create the secret resource here so the IAM grant exists at apply time, but
# the *value* is populated out of band:
#
#   echo -n "<your livesync passphrase>" | gcloud secrets versions add \
#     obsidian-livesync-passphrase --data-file=- --project=<project>
#
# `lifecycle.ignore_changes` on the version resource means Terraform won't
# try to overwrite the secret value once you've populated it.
#
# If path obfuscation is also on (recommended), the obfuscation passphrase is
# the same value LiveSync uses — currently the LiveSync plugin shares the E2EE
# passphrase for both purposes. Should that change, add a second secret here.

resource "google_secret_manager_secret" "obsidian_livesync_passphrase" {
  secret_id = "obsidian-livesync-passphrase"

  replication {
    auto {}
  }

  depends_on = [google_project_service.secret_manager]
}

# Placeholder so the secret has at least one version on first apply. We
# overwrite this manually with the real passphrase before deploying the
# service. ignore_changes prevents Terraform from clobbering it later.
resource "google_secret_manager_secret_version" "obsidian_livesync_passphrase_placeholder" {
  secret      = google_secret_manager_secret.obsidian_livesync_passphrase.id
  secret_data = "REPLACE_ME_WITH_THE_LIVESYNC_PASSPHRASE_FROM_YOUR_CLIENT"

  lifecycle {
    ignore_changes = [secret_data]
  }
}

resource "google_secret_manager_secret_iam_member" "obsidian_livesync_passphrase_accessor" {
  secret_id = google_secret_manager_secret.obsidian_livesync_passphrase.id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.obsidian_mcp.email}"
}

# ─── Bearer token (defence-in-depth, provider-independent) ──────────────────
#
# A second auth factor that sits inside the server, behind whatever external
# auth provider is in front (Cloudflare Access today, possibly IAP / OIDC
# tomorrow). Two reasons it exists:
#
#   1. If Cloudflare Access is misconfigured (policy too permissive, app
#      pointing at the wrong hostname, etc.) the bearer check still gates
#      access. Belt and braces.
#
#   2. It's provider-independent. When we migrate to a different external
#      auth, the bearer stays — we don't have to coordinate a flag-day on
#      the second factor.
#
# 48 chars, alphanumeric, no special chars (some HTTP clients are picky
# about Authorization header quoting).

resource "random_password" "obsidian_mcp_bearer_token" {
  length  = 48
  special = false
}

resource "google_secret_manager_secret" "obsidian_mcp_bearer_token" {
  secret_id = "obsidian-mcp-bearer-token"

  replication {
    auto {}
  }

  depends_on = [google_project_service.secret_manager]
}

resource "google_secret_manager_secret_version" "obsidian_mcp_bearer_token" {
  secret      = google_secret_manager_secret.obsidian_mcp_bearer_token.id
  secret_data = random_password.obsidian_mcp_bearer_token.result
}

resource "google_secret_manager_secret_iam_member" "obsidian_mcp_bearer_token_accessor" {
  secret_id = google_secret_manager_secret.obsidian_mcp_bearer_token.id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.obsidian_mcp.email}"
}

# ─── Cloud Run service ──────────────────────────────────────────────────────
#
# Sizing rationale:
#   - min_instance_count = 0   → scale to zero when idle. Cold starts are
#                                ~2-4s for a Node 22 container. Acceptable
#                                for a personal MCP that's used in bursts.
#                                If that's too slow, set this to 1 — costs
#                                a few dollars a month for an always-warm
#                                instance.
#   - max_instance_count = 2   → personal use, no need to scale wide. Caps
#                                blast radius if something gets stuck in
#                                a tight loop.
#   - concurrency        = 10  → MCP requests are streamable HTTP, mostly
#                                idle while waiting on CouchDB / Claude.
#                                Multi-concurrent fits one CPU comfortably.
#   - memory             = 512Mi → in-memory BM25 index over a personal
#                                vault sits comfortably under this even
#                                with thousands of notes.
#   - cpu                = 1, request-allocated → cheaper than always-on
#                                CPU. CPU is allocated only during request
#                                handling, which is fine because the
#                                background _changes feed reconnects on
#                                wakeup.
#
# `ingress = INGRESS_TRAFFIC_ALL` so the Cloudflare Tunnel can reach it
# from the e2-micro. We don't need internal-only ingress because the auth
# is enforced at Cloudflare Access AND inside the server.
#
# `allUsers` invoker means Cloud Run itself doesn't enforce auth — that's
# delegated to Cloudflare Access + our bearer-token check. This is the
# normal pattern for "auth is at the edge, not at Cloud Run".
#
# `value_source.secret_key_ref` mounts secret values as env vars at
# request time. The service account needs `roles/secretmanager.secretAccessor`
# on each — set above.

resource "google_cloud_run_v2_service" "obsidian_mcp" {
  name     = "obsidian-mcp"
  location = var.gcp_region

  ingress = "INGRESS_TRAFFIC_ALL"

  template {
    service_account = google_service_account.obsidian_mcp.email

    scaling {
      min_instance_count = 0
      max_instance_count = 2
    }

    max_instance_request_concurrency = 10

    containers {
      # First deploy uses a placeholder image; the deploy script
      # (scripts/obsidian-mcp/deploy.sh) updates this to a real tag built
      # from this repo. Terraform stops managing the image after first
      # apply via ignore_changes below.
      image = "us-docker.pkg.dev/cloudrun/container/hello"

      resources {
        cpu_idle          = true
        startup_cpu_boost = true

        limits = {
          cpu    = "1"
          memory = "512Mi"
        }
      }

      env {
        name  = "COUCHDB_URL"
        value = "https://${var.vault_subdomain}.${var.domain}"
      }

      env {
        name  = "COUCHDB_DB"
        value = var.obsidian_db_name
      }

      env {
        name  = "COUCHDB_USER"
        value = var.obsidian_mcp_couchdb_user
      }

      env {
        name  = "AUTH_PROVIDER"
        value = "cloudflare-access"
      }

      env {
        name  = "CF_ACCESS_TEAM_DOMAIN"
        value = var.cloudflare_access_team_domain
      }

      env {
        name  = "CF_ACCESS_AUD"
        value = var.cloudflare_access_aud
      }

      env {
        name  = "MCP_HOSTNAME"
        value = "${var.mcp_subdomain}.${var.domain}"
      }

      env {
        name  = "LOG_LEVEL"
        value = "info"
      }

      env {
        name = "COUCHDB_PASSWORD"
        value_source {
          secret_key_ref {
            secret  = google_secret_manager_secret.obsidian_mcp_couchdb_password.secret_id
            version = "latest"
          }
        }
      }

      env {
        name = "LIVESYNC_PASSPHRASE"
        value_source {
          secret_key_ref {
            secret  = google_secret_manager_secret.obsidian_livesync_passphrase.secret_id
            version = "latest"
          }
        }
      }

      env {
        name = "MCP_BEARER_TOKEN"
        value_source {
          secret_key_ref {
            secret  = google_secret_manager_secret.obsidian_mcp_bearer_token.secret_id
            version = "latest"
          }
        }
      }

      ports {
        container_port = 8080
      }
    }
  }

  traffic {
    type    = "TRAFFIC_TARGET_ALLOCATION_TYPE_LATEST"
    percent = 100
  }

  lifecycle {
    # The deploy script (scripts/obsidian-mcp/deploy.sh) is the source of
    # truth for the container image after first apply. Terraform creates the
    # service with a placeholder image; subsequent image rolls happen via
    # `gcloud run services update`. Terraform shouldn't fight that.
    ignore_changes = [
      template[0].containers[0].image,
      client,
      client_version,
    ]
  }

  depends_on = [
    google_project_service.cloud_run,
    google_secret_manager_secret_iam_member.obsidian_mcp_couchdb_password_accessor,
    google_secret_manager_secret_iam_member.obsidian_livesync_passphrase_accessor,
    google_secret_manager_secret_iam_member.obsidian_mcp_bearer_token_accessor,
  ]
}

# Public invoker. The Cloud Run service is not gated by Cloud Run IAM —
# auth is enforced upstream by Cloudflare Access and inside the server by
# the bearer-token check. See docs/obsidian-mcp/auth.md for the trust
# model and the migration recipe.
resource "google_cloud_run_v2_service_iam_member" "obsidian_mcp_invoker_public" {
  name     = google_cloud_run_v2_service.obsidian_mcp.name
  location = google_cloud_run_v2_service.obsidian_mcp.location
  role     = "roles/run.invoker"
  member   = "allUsers"
}
