# ─── GCP placement ──────────────────────────────────────────────────────────

variable "gcp_project_id" {
  type        = string
  description = "GCP project ID where infrastructure will be created."
}

variable "gcp_region" {
  type        = string
  description = "GCP region. Restricted to free-tier-eligible regions."
  default     = "us-east1"

  validation {
    condition     = contains(["us-east1", "us-west1", "us-central1"], var.gcp_region)
    error_message = "Region must be us-east1, us-west1, or us-central1 for the e2-micro free tier."
  }
}

variable "gcp_zone" {
  type        = string
  description = "GCP zone. Must be inside the chosen region. Note us-east1 has no '-a' zone — its zones are b/c/d."
  default     = "us-east1-b"

  validation {
    # Zone must be a real zone in the configured region. us-east1 is the odd
    # one out — it has no "-a" (the zones are b/c/d). lookup() with [] as the
    # fallback so an unknown region just returns "no valid zones" here and
    # the region-validation surfaces the actual cause.
    condition = contains(
      lookup({
        "us-east1"    = ["us-east1-b", "us-east1-c", "us-east1-d"]
        "us-west1"    = ["us-west1-a", "us-west1-b", "us-west1-c"]
        "us-central1" = ["us-central1-a", "us-central1-b", "us-central1-c", "us-central1-f"]
      }, var.gcp_region, []),
      var.gcp_zone
    )
    error_message = "Zone must be a real zone in the chosen region. us-east1 has b/c/d (no -a). us-west1 has a/b/c. us-central1 has a/b/c/f."
  }
}

# ─── Obsidian project ───────────────────────────────────────────────────────

variable "instance_name" {
  type        = string
  description = "Name of the GCE VM hosting CouchDB."
  default     = "obsidian-sync"
}

variable "obsidian_db_name" {
  type        = string
  description = "Name of the CouchDB database that will hold the Obsidian vault."
  default     = "obsidian"
}

variable "obsidian_admin_user" {
  type        = string
  description = "CouchDB admin username. The password is generated by Terraform and stored in Secret Manager."
  default     = "obsidian"
}

# ─── Cloudflare ─────────────────────────────────────────────────────────────

variable "domain" {
  type        = string
  description = "Apex domain registered at Cloudflare (e.g., niranjan.studio)."
}

variable "vault_subdomain" {
  type        = string
  description = "Subdomain that fronts CouchDB. Hostname becomes <vault_subdomain>.<domain>."
  default     = "vault"
}

variable "cloudflare_api_token" {
  type        = string
  description = "Cloudflare API token scoped to the domain zone. Required permissions: Zone:Read and DNS:Edit."
  sensitive   = true
}

variable "cloudflare_tunnel_id" {
  type        = string
  description = "Tunnel ID (UUID) emitted by `cloudflared tunnel create` on the VM. Leave empty on the first apply; the DNS record is skipped until this is set."
  default     = ""
}
