# ─── GCP placement ──────────────────────────────────────────────────────────

variable "gcp_project_id" {
  type        = string
  description = "GCP project ID where infrastructure will be created."
}

variable "gcp_region" {
  type        = string
  description = "GCP region. Restricted to free-tier-eligible regions."
  default     = "us-east1"

  validation {
    condition     = contains(["us-east1", "us-west1", "us-central1"], var.gcp_region)
    error_message = "Region must be us-east1, us-west1, or us-central1 for the e2-micro free tier."
  }
}

variable "gcp_zone" {
  type        = string
  description = "GCP zone. Must be inside the chosen region. Note us-east1 has no '-a' zone — its zones are b/c/d."
  default     = "us-east1-b"

  validation {
    condition = contains(
      lookup({
        "us-east1"    = ["us-east1-b", "us-east1-c", "us-east1-d"]
        "us-west1"    = ["us-west1-a", "us-west1-b", "us-west1-c"]
        "us-central1" = ["us-central1-a", "us-central1-b", "us-central1-c", "us-central1-f"]
      }, var.gcp_region, []),
      var.gcp_zone
    )
    error_message = "Zone must be a real zone in the chosen region. us-east1 has b/c/d (no -a). us-west1 has a/b/c. us-central1 has a/b/c/f."
  }
}

# ─── Obsidian project ───────────────────────────────────────────────────────

variable "instance_name" {
  type        = string
  description = "Name of the GCE VM hosting CouchDB."
  default     = "obsidian-sync"
}

variable "obsidian_db_name" {
  type        = string
  description = "Name of the CouchDB database that will hold the Obsidian vault."
  default     = "obsidian"
}

variable "obsidian_admin_user" {
  type        = string
  description = "CouchDB admin username. The password is generated by Terraform and stored in Secret Manager."
  default     = "obsidian"
}

# ─── Cloudflare (vault tunnel only) ─────────────────────────────────────────
#
# Cloudflare is the DNS provider for the apex domain and is responsible for
# the tunnel that exposes CouchDB at vault.<domain>. The MCP service does
# NOT traverse Cloudflare — see cloudflare.tf for the DNS-only mcp record.

variable "domain" {
  type        = string
  description = "Apex domain registered at Cloudflare (e.g., niranjan.studio)."
}

variable "vault_subdomain" {
  type        = string
  description = "Subdomain that fronts CouchDB. Hostname becomes <vault_subdomain>.<domain>."
  default     = "vault"
}

variable "cloudflare_api_token" {
  type        = string
  description = "Cloudflare API token scoped to the domain zone. Required permissions: Zone:Read and DNS:Edit."
  sensitive   = true
}

variable "cloudflare_tunnel_id" {
  type        = string
  description = "Tunnel ID (UUID) emitted by `cloudflared tunnel create` on the VM. Leave empty on the first apply; the DNS record is skipped until this is set."
  default     = ""
}

# ─── Obsidian MCP server (Phase 2) ──────────────────────────────────────────

variable "mcp_subdomain" {
  type        = string
  description = "Subdomain that fronts the MCP Cloud Run service. Hostname becomes <mcp_subdomain>.<domain>."
  default     = "mcp"
}

variable "obsidian_mcp_couchdb_user" {
  type        = string
  description = "CouchDB username used by the MCP server. Provisioned by scripts/obsidian-mcp/create-couchdb-user.sh with RW on the obsidian DB only — distinct from the Phase 1 admin user."
  default     = "obsidian-mcp"
}

variable "google_oauth_client_id" {
  type        = string
  description = "Google OAuth 2.0 Web application client_id. Created in GCP Console → APIs & Services → Credentials. The client_secret lives in Secret Manager (`obsidian-mcp-google-oauth-client-secret`)."
}

variable "mcp_allowed_emails" {
  type        = list(string)
  description = "Email addresses permitted to authenticate to the MCP service via Google OIDC. Lowercased, no whitespace. The server checks this set after Google verifies the user's identity."

  validation {
    condition     = length(var.mcp_allowed_emails) > 0
    error_message = "mcp_allowed_emails must list at least one email — leaving it empty would let any Google account in."
  }
}
