// Defence-in-depth bearer-token check. This runs ALONGSIDE whichever
// AuthProvider is configured — it is not a replacement for one. The bearer
// token is generated by Terraform, stored in Secret Manager, and provided
// to clients as part of the connection handshake.
//
// Why a second factor: if the upstream auth provider is misconfigured (an
// Access policy gets too permissive, an IAP backend gets pointed at the
// wrong service), the bearer check still gates access. This token is also
// provider-independent — it stays the same when the auth layer migrates.

import { Effect, Redacted } from "effect";
import { timingSafeEqual } from "node:crypto";
import { AuthError } from "../lib/errors.js";
import type { AuthRequest } from "./provider.js";

const constantTimeEqual = (a: string, b: string): boolean => {
  if (a.length !== b.length) {
    // Still do a comparison against `a` to keep timing close. Length leaks
    // anyway via the early-return; bearer tokens are fixed-length so this
    // is only ever hit by malformed input.
    return timingSafeEqual(Buffer.from(a), Buffer.from(a)) && false;
  }
  return timingSafeEqual(Buffer.from(a), Buffer.from(b));
};

export const verifyBearerToken = (
  req: AuthRequest,
  expected: Redacted.Redacted<string>,
): Effect.Effect<void, AuthError> =>
  Effect.sync(() => {
    const header = req.header("authorization");
    if (!header) {
      return new AuthError({
        reason: "missing Authorization header",
        statusCode: 401,
      });
    }
    const match = /^Bearer\s+(.+)$/i.exec(header.trim());
    if (!match) {
      return new AuthError({
        reason: "Authorization header is not a Bearer token",
        statusCode: 401,
      });
    }
    const presented = match[1] ?? "";
    if (!constantTimeEqual(presented, Redacted.value(expected))) {
      return new AuthError({
        reason: "bearer token did not match",
        statusCode: 403,
      });
    }
    return null;
  }).pipe(
    Effect.flatMap((err) => (err ? Effect.fail(err) : Effect.void)),
  );
